### ISSUE TITLE
Make compatible with Mopidy 1.0.0

### ISSUE THREAD

**Issue by Cysioland** [hechtus/mopidy-gmusic#78]
In logs I'm getting
```
WARNING  GMusicBackend does not implement playlists.as_list(). Please upgrade it.
```
And no playlists in my client software (ncmpcpp)

**Comment by Sguerso** [comment]
Same here after upgrading mopidy from 0.19.5-1 to 1.0.0-3

**Comment by morgoth** [comment]
Are you guys using this plugin from `develop` branch?
If not, can you try with `pip install https://github.com/hechtus/mopidy-gmusic/archive/develop.zip`

**Comment by riskersen** [comment]
Hey morgoth,

i tried your develop.zip, songs are displayed but not playable.

2015-04-17 21:15:01,797 - ERROR    Failed to lookup "Tsl44egzrz7zl3hpfauqnlljzci": GetStreamUrl: 404 Client Error: Not Found
(requests kwargs: {'headers': {'X-Device-ID': u'1234567890', 'Authorization': '<omitted>'}, 'params': {'opt': 'hi', 'mjck': u'Tsl44egzrz7zl3hpfauqnlljzci', 'pt': 'e', 'slt': '1429305301723', 'sig': 'n15DEMwJf_2QtFjP6GncnCEDOSo', 'net': 'wifi'}, 'url': 'https://android.clients.google.com/music/mplay', 'verify': False, 'allow_redirects': False, 'method': 'GET'})
(response was: '<HTML>\n<HEAD>\n<TITLE>Not Found</TITLE>\n</HEAD>\n<BODY BGCOLOR="#FFFFFF" TEXT="#000000">\n<H1>Not Found</H1>\n<H2>Error 404</H2>\n</BODY>\n</HTML>\n')

**Comment by brandonsturgeon** [comment]
Any update on this?

I see in the `params` : `'params': {'opt': 'hi', 'mjck': u'Tsl44egzrz7zl3hpfauqnlljzci', 'pt': 'e', 'slt': '1429305301723', 'sig': 'n15DEMwJf_2QtFjP6GncnCEDOSo', 'net': 'wifi'}` there's a 'hi" for the 'opt' key, not sure if that's a legit value or if that was just used for testing.

Anyway, would love to be able to use Gmusic!

**Comment by t4exanadu** [comment]
I'm having the same issue. My Google Play Music playlists are displayed, but clicking on songs does nothing (they don't play).

Also, are there any restrictions on logging into Google Play Music from this extension? I have two GMusic accounts. I see no authentication issues when I set my main account in the mopidy.conf. However, when I try my other account, I get authentication errors (I know the password and username are correct). My main account is the one tied to my Android device (this is the one that syncs all my apps and data to and from Google's servers). I wonder if this account is somehow tied to my Android Device ID.

**Comment by brandonsturgeon** [comment]
@t4exanadu Make sure the account you're trying to log into doesn't have Google's 2-step Authentication enabled.

If it does, it'll fail to login. To remedy this you'll need to go to your Google account settings and crete a new application-specific password.

https://security.google.com/settings/security/apppasswords

Select "Other" from the "Select App" pulldown,  give it a name "Mopidy Gmusic" or something. And generate a password, then use that generated password in your mopidy config.

If that's your problem, that should solve the "failed to login" issue. If it's not, then this doesn't really apply, ha ha.

**Comment by Cysioland** [comment]
Now works with the latest update.

**Comment by brandonsturgeon** [comment]
@Cysioland Is the latest version released? How can I update?

**Comment by Cysioland** [comment]
@brandonsturgeon I'm using an APT repository, if you want to, then here's my sources.list entry:
```sources.list
deb http://apt.mopidy.com/ stable main contrib non-free
deb-src http://apt.mopidy.com/ stable main contrib non-free
```

**Comment by t4exanadu** [comment]
@brandonsturgeon Two-step authentication is off for both accounts, so it's not that. Thank you for the suggestion, though.

**Comment by t4exanadu** [comment]
Still having some problems with GMusic with the latest version. I'm assuming it's the latest version, because I am using the repo listed above. I even re-installed mopidy and mopidy-gmusic from Synaptic to ensure it's the latest. Anyway, clicking on songs in playlists still does nothing (and I get a 403 client forbidden and "track not playable" errors in the Mopidy window). When I browse to an artist or album, no tracks are listed (for either artists or albums). Anyone else getting this?

**Comment by TheCrow1213** [comment]
@t4exanadu getting the same error. Looks like it's logging in correctly since I'm able to search tracks from google, but none of them will play. I get the same errors you do. I have two factor auth enabled but I'm using an app password.

**Comment by t4exanadu** [comment]
This was before the re-design, too. It's probably even more broken now (the redesign broke just about every Google Music-related app and extension I use). Hopefully it'll get up and running again sometime. I've been messing around with subsonic myself lately (it's OK, kind of sluggish, and I'm not super excited that it relies on java).

**Comment by TheCrow1213** [comment]
@t4exanadu for sure, Mopidy is working great with our other streaming services and was pretty quick and easy to set up.
